export compart="tissue"
export taxon="g__Diversicola"
export rdatasetup="/Users/Ryan/Dropbox/Selectively_Shared_Vega_Lab_Stuff/GCMP/Projects/Australia_Coevolution_Paper/16S_analysis/4_coevolution/output/mcmcglmm_subsets/endos_2/tissue/g__Diversicola_binary_presence/g__Diversicola_mcmc_setup.RData"
Rscript /Users/Ryan/Dropbox/Selectively_Shared_Vega_Lab_Stuff/GCMP/Projects/Australia_Coevolution_Paper/16S_analysis/4_coevolution/procedure/16_subsets/subset_endos_2/6c_run_mcmcglmm_coev_rel_20161219.r
