export compart="tissue"
export taxon="g__Coralicola_robust"
export rdatasetup="/Users/Ryan/Dropbox/Selectively_Shared_Vega_Lab_Stuff/GCMP/Projects/Australia_Coevolution_Paper/16S_analysis/4_coevolution/output/mcmcglmm_subsets/flavos_binary_presence/tissue/g__Coralicola_robust/g__Coralicola_robust_mcmc_setup.RData"
Rscript /Users/Ryan/Dropbox/Selectively_Shared_Vega_Lab_Stuff/GCMP/Projects/Australia_Coevolution_Paper/16S_analysis/4_coevolution/procedure/16_subsets/subset_flavos/6c_run_mcmcglmm_coev_rel_20161222.r
